"""Initial migration with all models

Revision ID: 463d592552ae
Revises: 8aa393287388
Create Date: 2025-08-08 01:08:37.730667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463d592552ae'
down_revision = '8aa393287388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
